### ISSUE TITLE
NPM is not updated with the latest version

### ISSUE THREAD

**Issue by russoedu** [sindresorhus/camelcase#100]
Hello there,

I installed the NPM package on my code and TS was complaining `preserveConsecutiveUppercase` was not one of the possible options and indeed, it's not in the `d.ts` file.

I forked the code to add it and make a pull request and then found out it's already (both `preserveConsecutiveUppercase` and `locale`) there, but the version on NPM doesn't have it yet.

Would you please publish this version that both the other options are set in the description?

Thanks!

**Comment by sindresorhus** [comment]
The latest version on npm is v7. The latest commit in this repo is v7.
