### ISSUE TITLE
pascal case broken when string ends with 1 number and 1 letter.

### ISSUE THREAD

**Issue by mpicard** [sindresorhus/camelcase#107]
# Reproduction

```js
camelcase("a1b", { pascalCase: true });
```

# Current Behaviour

```js
"A1b"
```

# Expected Behaviour

```js
"A1B"
```

**Comment by ddoumecq** [comment]
As far as I can tell this is intended behavior. Basically numbers are considered to be word breaks.

**Comment by skavigitp** [comment]
Ran a test for the above scenario and the test passed without errors. 
 ✔ pascal case broken with number
test('pascal case broken with number ', t => {
	t.is(camelCase('a1b', {pascalCase: true}), 'A1B');
});

**Comment by daniel-quinn-c1** [comment]
> Ran a test for the above scenario and the test passed without errors. ✔ pascal case broken with number test('pascal case broken with number ', t => { t.is(camelCase('a1b', {pascalCase: true}), 'A1B'); });

I also ran a few tests trying to break the functionality, but everything seems to work as it should. Even tried using double quotes as shown in the example, not that those should matter. Should this issue be closed?

✔️ Issue 107
test('Issue 107', t => {
	/* eslint-disable-next-line quotes */
	t.is(camelCase("a1b", {pascalCase: true}), "A1B");
	t.is(camelCase('a1b2c3', {pascalCase: true}), 'A1B2C3');
	t.is(camelCase('the1quick2brown3fox4jumped5over6the7lazy8red9dog10a', {pascalCase: true}), 'The1Quick2Brown3Fox4Jumped5Over6The7Lazy8Red9Dog10A');
	t.is(camelCase('the1quick2brown_3fox4jumped5over6The7lazy8red9dog10a', {pascalCase: true}), 'The1Quick2Brown3Fox4Jumped5Over6The7Lazy8Red9Dog10A');
});
