### ISSUE TITLE
already camel case segment become lowercase

### ISSUE THREAD

**Issue by MathieuDoyon** [sindresorhus/camelcase#11]
'fooFoo bar' → 'foofooBar'

should be 'fooFooBar'

**Comment by Qix-** [comment]
Could have sworn we had a test for this...

**Comment by Kepro** [comment]
maybe this answer? http://stackoverflow.com/a/15829686

**Comment by egoldblum** [comment]
Seems the test disagrees? https://github.com/sindresorhus/camelcase/blob/master/test.js#L25

I expected the same behavior as the OP.

**Comment by sindresorhus** [comment]
It should preserve any existing camelCase. The test is incorrect. PR welcome for a fix :)
