### ISSUE TITLE
Symbols are prepended with dash

### ISSUE THREAD

**Issue by jvamvas** [sindresorhus/camelcase#14]
I am not sure whether this is in the scope of this project but I noticed that in some cases symbols are prepended with a dash where I expected them to stay the same or to be deleted.

Example tests:

```javascript
test('camelCase', t => {
        t.is(fn('foo bar?'), 'fooBar?');  // or 'fooBar'
        t.is(fn('foo bar!'), 'fooBar!');
        t.is(fn('foo bar$'), 'fooBar$');
        t.is(fn('foo-bar#'), 'fooBar#');
});
```

Camelcase output:
```javascript
"fooBar-?"
"fooBar-!" 
"foo- $bar"
"fooBar-#"
```

**Comment by portgasd666** [comment]
This is caused by the c === c.toUpperCase() test in preserveCamelCase which returns true for non alphabet characters.
