### ISSUE TITLE
Using `let` limits browser and node support

### ISSUE THREAD

**Issue by atkinchris** [sindresorhus/camelcase#19]
This commit (https://github.com/sindresorhus/camelcase/commit/2296030d560d4620eb1773219686822eb9c322e3) replaces `var` with `let` for ES2015 style. However, the `let` syntax is not widely supported, and breaks with some toolsets, such as uglify.

This could be resolved by:

* Reverting to supported syntax of `var`, or
* Transpile the `npm` published version to ES5.

**Comment by atkinchris** [comment]
Two accidental keystrokes, and I created an issue. I'm sorry. 😿

**Comment by sindresorhus** [comment]
This module mainly targets Node.js. If you want to use it in the browser it's up to you to resolve it, like transpiling it with Babel.

**Comment by futpib** [comment]
What about adding publishing a transpiled file and adding a `browser` field to `package.json` for easy usage with browserify/webpack? Would such PR be welcome or not?
