### ISSUE TITLE
UglifyJS issue

### ISSUE THREAD

**Issue by yanickrochon** [sindresorhus/camelcase#21]
While building a meteor app, I got this error

```
UglifyJS minification error:

SyntaxError: Unexpected token: name (isLastCharLower) at
node_modules/camelcase/index.js line 4
```

It seems odd to me that this line would throw an error, but here we are.

**Comment by yanickrochon** [comment]
Since the module uses ES2015 arrow functions, it is not compatible with client side code. I believe Meteor.js is working to enable Babel for node modules, but we are not there yet.

Note that arrow functions are still slower than legacy functions... I don't know why everyone use it everywhere already.

**Comment by Qix-** [comment]
I'll let @sindresorhus respond to this (:

**Comment by mozillo** [comment]
Got same error

**Comment by sindresorhus** [comment]
> Note that arrow functions are still slower than legacy functions...

No: https://kpdecker.github.io/six-speed/

**Comment by sindresorhus** [comment]
See: https://github.com/sindresorhus/ama/issues/446

**Comment by yanickrochon** [comment]
@sindresorhus what do you mean "no"? The link you suggest shows that declarations are generally 1.4x slower! Thus, in the [actual implementation](https://github.com/sindresorhus/camelcase/blob/9f613165326d52156dd059c0b308b758e7d54d3b/index.js#L32), you are effectively declaring arrow functions 3 times. Therefore, my statement is completely valid.

But this is beside the main issue; this module cannot be used on client side as it does not provide a browser friendly source, and UglifyJS fails.

You closed this issue without addressing the real problem.

**Comment by sindresorhus** [comment]
The `arrow` test shows it's identical. Even if it's 1.2x, that's pretty negligible in practice.

> You closed this issue without addressing the real problem.

I linked to https://github.com/sindresorhus/ama/issues/446. I don't have the time to answer this every time it comes up.
