### ISSUE TITLE
mis-specification

### ISSUE THREAD

**Issue by ORESoftware** [sindresorhus/camelcase#22]
IMO, this lib was mis-specified

the existing results: 

```js
camelCase('foo_bar');
//=> 'fooBar' 
 
camelCase('Foo-Bar');
//=> 'fooBar'  
```

should be this instead:

```js

camelCase('foo_bar');
//=> 'fooBar' 
 
camelCase('Foo-Bar');
//=> 'FooBar'                     // notice uppercase first letter...
```

but it's too late to change the API as it is - but perhaps you will accept a second argument, like so:

```js
camelCase('Foo-Bar', false);
//=> 'fooBar'  

camelCase('Foo-Bar', true);
//=> 'FooBar'  

```

camel case names *can* have an uppercase first letter! :)  This seems like a strange oversight, or maybe I am missing something. In other words, PascalCase is a special case of camelCase, they are not exclusive in my mind.

Would you accept a PR for this?

**Comment by ORESoftware** [comment]
nevermind, I read the whole readme, I see there is this library  https://github.com/SamVerschueren/uppercamelcase

however, neither of the libraries is the correct behavior, what should be is:

```
foo-bar => fooBar
Foo-Bar => FooBar
```

oh well I will figure out

**Comment by sindresorhus** [comment]
What you describe would be a very surprising default behavior. I don't think anyone else would expect that. Could be an option though.

**Comment by Qix-** [comment]
The second example isn't, by definition, camel case. It's title case. It would be a mis-specification for this library to behave like that.

**Comment by ORESoftware** [comment]
@Qix- I think that's false. Java is a camelCase language, so is JS. PascalCase is a special case of camelCase.  JS is camelCase as well. Constructors, singletons, etc, usually have PascalCase constructors or variable names:

```js
function ThisIsAConstructor(){

}
```

that is camelCase. It's just a backwards camel :)

```js
rotcurtsnoCAsIsihT
```

:)

**Comment by ORESoftware** [comment]
```
Wikipedia says

Camel case may start with a capital letter (called PascalCase or UpperCamelCase) or, especially in programming languages, with a lowercase letter.
```

you're just wrong :)

**Comment by ORESoftware** [comment]
This guy on Quora says it perfectly:

In general both can be considered equivalent although by definition "CamelCase" is a valid camel-cased word. Hence, PascalCase can be considered to be a subset of camelCase.

**Comment by sindresorhus** [comment]
@ORESoftware I don't disagree PascalCase is a subset. Only that getting different output depending on the input would be surprising for this module. It's explicitly for converting to camelCase, not PascalCase. I've said an option could make sense, but it's not a good default.

**Comment by ORESoftware** [comment]
Yeah not a big deal, I might add an option with PR at some point, thanks

**Comment by JulianRaya** [comment]
Y'all are thinking about it too hard... a camel's head is just as high as either of it's humps, unless its head is down.  It can be either way. 

@Qix- I'm pretty sure "Title Case" is really only for space separated words and only the important words are capitalized. In CamelCase, one would capitalize words like "of", "or", "and", and or "is".

**Comment by YounGoat** [comment]
Why not create a customized case to cease the dispute. E.g.
```javascript
const leca = require('leca');
let ci = new leca.Case({
    splitter: /[\s\-_]/,
    wordFormatter: (word, index) => {
        let init = word.charAt(0), remainder = word.substr(1).toLowerCase();
        init = (index == 0) ? init : init.toUpperCase();
        return init + remainder;
    },
});

ci.reformat('foo_bar'); 
// RETURN fooBar

ci.reformat('Foo-bar');
// RETURN FooBar

ci.reformat('FOO-BAR');
// RETURN FooBar
```
See [README of __leca__](https://www.npmjs.com/package/leca) for more details.

**Comment by PedroMiguelSS** [comment]
I saw that you can have multiple arguments like `camelCase('__foo__', '--bar');` and the output remains `'fooBar'`.
So, do you want an extra boolean argument (as @ORESoftware suggested) to indicate whether the output should be PascalCase or not?

I mean:

```
camelCase('Foo-Bar', false);
//=> 'fooBar'

camelCase('Foo-Bar', true);
//=> 'FooBar'

camelCase('Foo-Bar');
//=> 'fooBar'

camelCase('Foo','Bar', true);
//=> 'FooBar'

camelCase('Foo','Bar', false);
//=> 'fooBar'

camelCase('Foo','Bar');
//=> 'fooBar'
```


Or are you thinking in a completely different way to solve this?

**Comment by sindresorhus** [comment]
@PedroMiguelSS I think it's worth doing a breaking change and instead of supporting multiple arguments, just accept either a string or an array of strings. Then we can add a second argument for an options-object.

```js
camelCase(['Foo', 'Bar'], {pascalCase: true});
```

You can see how to document it here: https://github.com/sindresorhus/boxen#boxeninput-options
