### ISSUE TITLE
Add a .npmignore

### ISSUE THREAD

**Issue by alvinsight** [sindresorhus/camelcase#24]
Hi,
It would be great to add a `.npmignore` file to this repository so the `.editorconfig` `travis.yml` and `test.js` aren't included in the package when it's used as a dependency.
Ideally it would be something to do in all your repos, but this one is used *a lot*.
Thanks,
Alvin

**Comment by Qix-** [comment]
Hi, most of Sindre's modules use the `"files"` key in _package.json_, which acts as a files whitelist. Only _index.js_ is published.

Thanks!

**Comment by alvinsight** [comment]
Ah, nice one!
I didn't know about this feature, awesome!
I'm really impressed by the response time, good job man :)

**Comment by SamVerschueren** [comment]
`.npmignore` is blacklisting, it's much better to use whitelisting as defined [here](https://github.com/sindresorhus/camelcase/blob/master/package.json#L19).

@Qix- was faster :p

**Comment by Qix-** [comment]
![](https://media0.giphy.com/media/xUA7aTvAzOyPJH5aG4/giphy.gif)
