### ISSUE TITLE
Throws error in Internet Explorer 11

### ISSUE THREAD

**Issue by tylershuster** [sindresorhus/camelcase#29]
I'm using this module in a Meteor project and when it's inquired, it causes first a syntax error [here](https://github.com/sindresorhus/camelcase/blob/0e6e4a2752aa013b8e9477145c7b8132c95a82ef/index.js#L35) and then an unrecognized character error [here](https://github.com/sindresorhus/camelcase/blob/0e6e4a2752aa013b8e9477145c7b8132c95a82ef/index.js#L12) when the arrow functions are replaced with ES5 functions.

**Comment by Qix-** [comment]
Hi - you need to use Babel to make ES6 compatible with IE11.

**Comment by sindresorhus** [comment]
Duplicate of https://github.com/sindresorhus/camelcase/issues/23
