### ISSUE TITLE
Publish the code in ES5 to npm

### ISSUE THREAD

**Issue by utsavnarayan** [sindresorhus/camelcase#30]
'npm run build' fails to minify because index.js is using 'let' and arrow functions.

Refer:
https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

I can create a pull-request if you would like to downgrade to ES5.

**Comment by sindresorhus** [comment]
Duplicate of #23
