### ISSUE TITLE
Update README to include browser support

### ISSUE THREAD

**Issue by thenickcox** [sindresorhus/camelcase#38]
This module is great (just like all your other work!), but I included it in my project without realizing it targeted Node. I know it's my fault for not checking, so I don't blame you at all, but it broke my JS file for an IE11 customer. Would you accept a PR that mentions compatible browsers? If so, I'm happy to work that up.

**Comment by sindresorhus** [comment]
No, sorry, this module is mainly for Node.js. I'm not interested in bloating the readme with that, and it will have to be maintained too. For browser usage, transpiling everything is the best and safest option if you cannot target the latest versions of browsers.
