### ISSUE TITLE
Edge cases

### ISSUE THREAD

**Issue by slava-sh** [sindresorhus/camelcase#4]
```js
> camelCase('', '')
'-'
> camelCase(' ')
TypeError: Cannot read property 'toLowerCase' of undefined
```
I think it should return an empty string in both cases.

**Comment by sindresorhus** [comment]
@Qix-

**Comment by Qix-** [comment]
Thanks for this. Added tests and made a fix; it was simpler than even I expected. :+1: Definitely not edge cases imo.
