### ISSUE TITLE
treating none alphabetic characters

### ISSUE THREAD

**Issue by sprzybylski** [sindresorhus/camelcase#42]
I'm using ``camelcase`` to deal with css class names.
I'd like to transform css classes like ``m-grid-col6@md`` to camelCase notation ``mGridCol6@md`` and it works perfectly, but sometime I got input already camelCased(its due to React and its props) and it transform into ``mGridCol6-@md`` which is unwanted from my perspective.

Test case not passing:
```
t.is(m('mGridCol6@md'), 'mGridCol6@md');
```

I've came with two solutions:
1. change the way how ``camecase`` is checking case of character
```
isLastCharLower = c.toLowerCase() === c && c.toUpperCase() !== c;
isLastLastCharUpper = isLastCharUpper;
isLastCharUpper = c.toUpperCase() === c && c.toLowerCase() !== c;
```
2. widen the regexp in te final replace: ``/[_.\- ]+(\w|$)/g`` insted of   ``/[_.\- ]+(\.|$)/g``

But unfortunately that changes the behaviour in the following case:
```
t.is(m('@M'), '@M');
```

I'm happy to provide a PR but need suggestion how would you like to deal with it, if ever.

**Comment by iamahuman** [comment]
This is significant since it means it would also break on cases like "C😂a" since the extra dash would separate those two UTF-16 surrogates consisting the emoji. The algorithm is otherwise trivially "SMP-compliant" without furthur modifications.

**Comment by sindresorhus** [comment]
I would first look at how other camelCase packages/methods do it, like the one in Lodash, etc. Having some data would make it easier to make a decision.

**Comment by DanielSeehausen** [comment]
@sprzybylski @iamahuman @sindresorhus

recently used this package in a pinch and wanted to give back. Went ahead and opened a PR with tests that should fix the issue, the same as @sprzybylski 's first solution. the first option seemed more appropriate, as this was an issue with whether a letter was an upper or lower case in the parsing loop.

The fix ensures that characters that do not have case (this includes `:`) will no longer evaluate as upper or lower case!
