### ISSUE TITLE
Default exports vs module.exports = ...

### ISSUE THREAD

**Issue by sarunint** [sindresorhus/camelcase#51]
Regarding this comment:

https://github.com/sindresorhus/camelcase/blob/75014061a127d6e2c35503059605c4f655fe66db/index.js#L78-L79

It seems that this way of importing `camelcase`:

```
import camelCase from 'camelcase';
```

is deprecated in favour of:

```
import camelCase = require('camelcase');
```

I'm strongly opposed to this, since the second is not in JavaScript standard. (`require` is a CommonJS syntax?)

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import

Please take a look and let me know what do you think about this.

**Comment by sindresorhus** [comment]
See https://github.com/sindresorhus/mem/issues/31 for why the change was needed. Just use this https://github.com/sindresorhus/tsconfig/blob/d4a760348b9c1e3f3acfd4f351484583ce498c06/tsconfig.json#L9-L10 in your tsconfig to be able to import it with `import camelCase from 'camelcase';`.
