### ISSUE TITLE
c('Hello1World')

### ISSUE THREAD

**Issue by eladb** [sindresorhus/camelcase#52]
Seems like the fix to #42 changes the behavior of identifying word breaks after numbers:

Pre 5.3.0:

```
camelcase('Hello1World') === 'hello1World'
```

5.3.0:

```
camelcase('Hello1World') === 'hello1world';
```

I guess it's a matter of opinion, but the previous behavior does seem more like what people would expect. At any rate, if this is the intended behavior, I would have preferred a major version bump.

**Comment by Qix-** [comment]
I agree that the previous output seems more correct.

**Comment by DanielSeehausen** [comment]
oh my lord this is my fault - i will work on a fix asap!

**Comment by eladb** [comment]
Thanks guys!

**Comment by Qix-** [comment]
@DanielSeehausen Let's make sure to add a test for this case :+1:

**Comment by DanielSeehausen** [comment]
@eladb @Qix- @sindresorhus 
fix is up for this

Please take a moment to peak at the added tests carefully, and make sure that is the behavior you are looking for! Particularly the `1Hello` behavior. Happy to make any changes requested. 

The regex could be squashed together for sure, but that gets a little harry and I found it less explicit (but I don't have any objections if anyone wants to change)
