### ISSUE TITLE
c('e2e')

### ISSUE THREAD

**Issue by dazip** [sindresorhus/camelcase#54]
Seems like the regression fix to #53 creates another regression

5.3.0:

camelcase('e2e') === 'e2e';

5.3.1:

camelcase('e2e') === 'e2E';

**Comment by dazip** [comment]
The new behavior is consistent with lodash.camelcase
- https://www.npmjs.com/package/lodash.camelcase

The old behavior is consistent with case.camel
- https://www.npmjs.com/package/case

**Comment by sindresorhus** [comment]
Not really sure which one is the most appropriate. I'm leaning towards `e2E`.

// @DanielSeehausen @eladb @Qix-

**Comment by Qix-** [comment]
Yep agreed.

**Comment by eladb** [comment]
golly... so many edge cases. Is this a unique case because after the number there’s only a single character?

**Comment by dazip** [comment]
Same would apply for any number of characters after the numeric. Please consider whether it would be appropriate to revert to 5.2.0 behavior in 5.x.x and bump to 6.0.0 for 5.3.0/5.3.1 changes.

**Comment by sindresorhus** [comment]
Alright, let's keep the current behavior.

**Comment by sindresorhus** [comment]
> Please consider whether it would be appropriate to revert to 5.2.0 behavior in 5.x.x

That would be a breaking change for people depending on the new behavior, so not going to happen. Better to just leave it like this.

**Comment by DanielSeehausen** [comment]
sorry for late reply -- just seeing this!
e2E would also be my vote, as numbers should act as delimiters in camel casing!
seems to follow the original intent of the code as well, and know lodash has been mentioned as a north star here.
