### ISSUE TITLE
Correctly handle Unicode characters

### ISSUE THREAD

**Issue by sunknudsen** [sindresorhus/camelcase#60]
The regular expressions in this package don’t support unicode characters such as `àçéèù` so `camelCase("Licorne époustouflante")` outputs `licorne époustouflante`.

Perhaps we could add a `transliterate` option that leverages [transliterate](https://www.npmjs.com/package/@sindresorhus/transliterate) so `camelCase("Licorne époustouflante", { transliterate: true })` outputs `licorneEpoustouflante`.

Another slightly more complicated alternative would be to have `camelCase("Licorne époustouflante", { transliterate: true })` output `licorneÉpoustouflante`.

What do you think? I could put a PR together.

**Comment by sunknudsen** [comment]
Perhaps adding a `camelcase` option to `@sindresorhus/slugify` might a better alternative.

Looking for a way to convert any JavaScript property name (which can include all unicode characters) to camel case.

**Comment by sindresorhus** [comment]
A better way would be for the regexes used here to use Unicode property escapes, like done in https://github.com/sindresorhus/decamelize/blob/b445ed47a5548e2ba8fe41889807d17879faa7c5/index.js#L9-L10

**Comment by sverweij** [comment]
@sunknudsen / @sindresorhus I've put up a fix for this (see☝️, PR #62) which employs Unicode property escapes as suggested.

You can test whether it works for your use case  by running `npm install sverweij/camelcase`. This will install it directly from the forked repo on github - the code will live there only until it's merged into this repo. Or when a better fix comes along, of course :-)
