### ISSUE TITLE
'SyntaxError: invalid identity escape in regular expression' in Firefox after upgrading to v6.0.0

### ISSUE THREAD

**Issue by apasov** [sindresorhus/camelcase#63]
I get this error in Firefox only:
`SyntaxError: invalid identity escape in regular expression`
though in Chrome it works okay.
![image](https://user-images.githubusercontent.com/28765662/78712601-23ccf780-7919-11ea-8612-026ab8e16573.png)

Steps to reproduce:
```
git clone https://github.com/apasov/animatable-properties.git
cd animatable-properties
git reset --hard 3728a084984482ddcfc6a096a38c9b4c10a8c270
```
then open index.html in Firefox and you'll see blank page and the error in console.

After this commit [fix: downgrade to camelcase v5.3.1 to fix syntax error in Firefox ](https://github.com/apasov/animatable-properties/commit/cd3bda8f6a5972e7af4a71c5b65a3616c2852b01) which fixes the error
```
git reset --hard cd3bda8f6a5972e7af4a71c5b65a3616c2852b01
```
reload index.html and it works as intended without errors

**Comment by EthanSbbn** [comment]
Same issue on node 8.15.0

`SyntaxError: Invalid regular expression: /[\p{Lu}]/: Invalid escape`

**Comment by EthanSbbn** [comment]
It's not a resolved issue @sindresorhus

I still have the same error in Node.
Lot of code depending on your package will fail if they update.

**Comment by sindresorhus** [comment]
@EthanSbbn Your issue is just that you didn't read the [release notes](https://github.com/sindresorhus/camelcase/releases) which clearly state that Node.js 10 is required now.

**Comment by EthanSbbn** [comment]
@sindresorhus You should put it on the README. Such an information, is quite important :)

**Comment by sindresorhus** [comment]
No, it’s expected that you read release notes. Especially for major versions.

**Comment by phun-ky** [comment]
@sindresorhus I have nodejs 12.16.3, and I get:

```
SyntaxError: invalid identity escape in regular expression
```

In firefox, with v6, but will downgrade. So it's not just a "You need a newer node version" issue. Perhaps specify that this is a ES2018 issue?

**Comment by sindresorhus** [comment]
@phun-ky Tests are passing on 12.16.3: https://travis-ci.com/github/sindresorhus/camelcase/jobs/321547607 You probably have multiple Node.js versions installed.

**Comment by phun-ky** [comment]
Hm, I use nvm, but the package is built / installed with the current node version active, as per spec right? For example, node sass (deps? ) needs to be recompiled/installed if you change versions.

Is not an issue for me, but dont be hasty saying that everything works just because the test passes.

**Comment by ThiefMaster** [comment]
```
SyntaxError: Invalid regular expression: /[_.\- ]+([\p{Alpha}\p{N}_]|$)/: Invalid property name in character class
    at camelCase (/home/adrian/dev/indico/src/node_modules/jest-validate/node_modules/camelcase/index.js:69:3)
```

With nodejs 12.16.1 on Gentoo.
