### ISSUE TITLE
Case conversion with specific locale

### ISSUE THREAD

**Issue by rasgele** [sindresorhus/camelcase#72]
Case conversion are done with `String.prototype.toLocaleLowerCase()` and `String.prototype.toLocaleUpperCase()` without explicit locale parameter and this causes host dependent output.
Example:
```js
camelCase('lorem-ipsum')
//=> 'loremIpsum' if host locale is en-US
//=> 'loremİpsum' if host locale is tr-TR
```
This causes unexpected results int hosts with non en-US environment.

I'd suggest to extend `options` parameter to have a `locale` property to be passed to aforementioned methods.

```js
camelCase('lorem-ipsum', {locale: 'en-US'});
//=> 'loremIpsum' if host locale is en-US
//=> 'loremIpsum' if host locale is tr-TR
```

**Comment by selimrecep** [comment]
I am experiencing same issue too. Just because of this error, I couldn't get Jest work without workarounds.

**Comment by selimrecep** [comment]
I have opened PR. I think that will fix it.

**Comment by rasgele** [comment]
@selimrecep Sorry, in parallel I've also submitted a PR. Any of them is fine :)
