### ISSUE TITLE
Converting either volume_3d or volume3d results in volume3D making it impossible to decamelize

### ISSUE THREAD

**Issue by fc** [sindresorhus/camelcase#77]
How to reproduce:
```
console.log(camelcase('volume_3d')); // volume3D
console.log(camelcase('volume3d')); // volume3D
```

this operates under the assumption that decamelizing should return the string to its original decamelized version but I'm not sure how that would be possible for strings in this format.

**Comment by sindresorhus** [comment]
What would expect the second case to camelize to?

**Comment by fc** [comment]
This is what I was thinking:
`volume_3d` -> `volume3d`
`volume3d` -> `volume3D`
That's the only way I can imagine it working while still allowing a way to reverse it to its original form.

**Comment by Qix-** [comment]
Seems inconsistent. I'm :-1:.

In your two examples, you have two different conventions: `snake_case` and `lowercase`.

- `volume3D` in snake_case is `volume_3d`
- `volume3D` in lowercase is `volume3d`

Seems to reverse correctly to me.

**Comment by fc** [comment]
Some context... using `decamelize` right now converts `volume3D` to `volume3_d`.
Am I right to assume that calling `decamelize` should revert the string to its original camelcased form?

**Comment by sindresorhus** [comment]
The conversion to/from camel-case is not stable and I don't think it's feasible or even ideal to do so. I think the solution here is to document in both readme's that you cannot assume stability both ways.

**Comment by dangreen** [comment]
Hi. I'v got same problems:

Expected: b2b_registration_request -> b2bRegistrationRequest 
Received: b2b_registration_request -> b2BRegistrationRequest

Most other same libs works as expected, but we use `camelcase-keys` package which use this package.

**Comment by dangreen** [comment]
Libs examples:

```
> require('to-camel-case')('b2b_registration_request')
'b2bRegistrationRequest'
> require('to-snake-case')('b2bRegistrationRequest')
'b2b_registration_request'
> require('decamelize')('b2bRegistrationRequest')
'b2b_registration_request'
```

**Comment by emmanuelsio** [comment]
I have the same issue

```
var camelcaseKeys = require("camelcase-keys")
camelcaseKeys({'uses_log4j': true}); 
//=> usesLog4J
```
Why after number makes upper case the following character? 
The result migth be usesLog4j

**Comment by sindresorhus** [comment]
> Expected: b2b_registration_request -> b2bRegistrationRequest

I agree. That should be fixed. PR welcome.

**Comment by JCrandall101** [comment]
Hey @sindresorhus, I open [PR-112](https://github.com/sindresorhus/camelcase/pull/112) to be able to handle the b2b_registration_request issue. Is this what you were looking for?
