### ISSUE TITLE
SyntaxError: Invalid regular expression: /[\p{Lu}]/: Invalid escape

### ISSUE THREAD

**Issue by ityancs** [sindresorhus/camelcase#90]
const UPPERCASE = /[\p{Lu}]/u;

will throw the exception when deploy。

**Comment by sindresorhus** [comment]
Duplicate of #88

**Comment by ityancs** [comment]
@sindresorhus Thank you for your reply. How to add a parser to solve this problem in detail? I think many beginners will still be confused.

**Comment by ityancs** [comment]
I actually saw this and that question before, I think you explained it very clearly, but it is still very confusing for beginners. Can you give some examples?

**Comment by sindresorhus** [comment]
This is a problem with your build tool, not this package. You should open an issue there instead.
