### ISSUE TITLE
"Invalid regular expression: /[\p{Lu}]/: Invalid escape" after updating to version 6.2.1

### ISSUE THREAD

**Issue by ASiumkin** [sindresorhus/camelcase#91]
Hello,

just FYI, it seems like version 6.2.1 broke css-loader that was working perfectly fine using NodeJS v8. 
And yes, I understand that both libraries require node v10+, but it was working perfectly fine.

My build started to fail with this error "Invalid regular expression: /[\p{Lu}]/: Invalid escape" and after a while, I found your library as css-loader's dependency that has been updated from version 6.2.0 to 6.2.1

Updating NodeJS version fixed the issue, but still this is something that shouldn't happen as a minor patch :)

This issue is created for the people who will encounter the same problem, hope this helps

**Comment by sindresorhus** [comment]
> but still this is something that shouldn't happen as a minor patch :)

Of course it can. It was not a breaking change as it's using a feature available in Node.js 10 and the defined package target is Node.js 10. If you choose to not follow the minimum Node.js 10, you are on your own.
