### ISSUE TITLE
"Invalid regular expression: /[\p{Lu}]/: Invalid escape" after updating to version 6.2.1

### ISSUE THREAD

**Issue by vinod-philip** [sindresorhus/camelcase#94]
I am using Node v12.22.3 and npm 6.14.13. As soon I upgrade to 6.2.1 I am getting **const UPPERCASE = /[\p{Lu}]/u;** 
invalid expression error on the build, but it works with version 6.2.0. Is there anything I am missing here? Please Verify. thanks

**Comment by sindresorhus** [comment]
That is a problem with your build system, not this package.

**Comment by Dozalex** [comment]
For those who have encountered the same problem while supporting older versions of browsers using Babel and Webpack, you should add this package to the rule for parsing it with Babel
```js
{
  test: /\.(tsx?|js)$/,
  exclude: /node_modules\/(?!camelcase)/,
  use: [
    { loader: 'babel-loader' },
  ],
},
```
