### ISSUE TITLE
"IDs" isn't camelized well

### ISSUE THREAD

**Issue by yunics-highfield** [sindresorhus/camelcase#95]
I'm using camelcase-keys@~~7.0.1~~7.0.2. I think `IDs` should be `ids` and `AmazingIDs` should be `amazingIds`. We might need more options to decide how to camelize.

https://stackblitz.com/edit/js-d8cpct?file=index.js

**Comment by sindresorhus** [comment]
> I think IDs should be ids and AmazingIDs should be amazingIds.

Correct 👍

**Comment by sindresorhus** [comment]
I have added some assertions for the correct behavior: https://github.com/sindresorhus/camelcase/commit/e527576105e86837521d0a5307b81352f7190239
